# Usa una imagen base de Go
FROM golang:1.23-alpine

# Instala herramientas necesarias
RUN apk add --no-cache git

# Crea un directorio de trabajo
WORKDIR /app

# Copia los archivos de módulo de Go
COPY go.mod go.sum ./

# Descarga las dependencias
RUN go mod download

# Copia el resto del código
COPY . .

# Compila el binario
RUN go build -o main .

# Define el comando por defecto
CMD ["./main"]

