version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=192.168.1.14
      - DB_PORT=3306
      - DB_USER=admin_UV_DB
      - DB_PASSWORD=982h78r7h47748h
      - DB_NAME=UV_DB
