# Usar la imagen base de Go
FROM golang:1.23-alpine

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos necesarios
COPY go.mod go.sum ./
RUN go mod download
RUN go get github.com/jung-kurt/gofpdf

COPY . .

# Compilar el binario
RUN go build -o main .

# Comando para ejecutar la aplicación
CMD ["./main"]

